debug_task:
  description: >
    debug given code: {input} {function}
    ** important **
    ----
    always implement:
      - disregard the debugging decorator in your solution
      - leave the original imports in the file
      - read carefully and change only the failed function, leave the others as they are
      - add comments on what was fixed and why
      - fixed functions should contain docstring, type hints and arrow functions 

  expected_output: >
    new clean python solution
  agent: debug_agent
