vision_task:
  description: >
    Analyze images to extract relevant information based on specified search terms.
    Search these terms: {image}
  expected_output: >
    Extracted relevant information from the provided images.
  agent: vision_agent
