evaluation_task:
    description: "{input} Evaluate the given task, define its category, and outline a strategic execution plan."
    expected_output: "A high-level task strategy with priorities and execution direction."
    agent: visionary_strategist

logical_task:
    description: "{input} Break down the given task into its fundamental components and identify key elements for execution."
    expected_output: "A structured breakdown of the task with actionable steps."
    agent: logical_analyst

orchestration_task:
    description: "{input} Optimize task execution order, resolve dependencies, and ensure an efficient workflow."
    expected_output: "An optimized workflow with prioritized task execution order."
    agent: adaptive_orchestrator

compliance_task:
    description: "{input} Assess the task for compliance with best practices, identify potential risks, and validate technical feasibility."
    expected_output: "A compliance report with risk assessment and recommendations."
    agent: compliance_evaluator

execution_task:
    description: "{input} Execute the final task based on the structured plan and validate the output against expectations."
    expected_output: "A completed task with a validation report and final adjustments if necessary."
    agent: execution_commander
