task:
  agent: agent
  description: |
    
    Validate the this image analysis:
    {image_analysis} 
    compare the image analysis with the prompt: {prompt}
    Use the chain_of_thought_process as the key source for validation.
    
    Decision rules:
    - If the chain_of_thought_process clearly supports a correct and coherent final decision, return `Passed`.
    - If the chain_of_thought_process is incorrect, unclear, or missing, return `Failed`.
    - If the reasoning process is partially complete or the conclusion is ambiguous, return `Inconclusive`.

  expected_output: |
    One of the following three responses only:
      - Passed
      - Failed
      - Inconclusive
