test_plan_task:
  description: >
    Conduct a thorough research about this test plan {test_plan}
    Make sure you find you review carefully step by step
  expected_output: >
    Validation for the test plan, return a thought about the test plan, add points for improvement
    and re-write them in a new test plan in correct .md file format as given above
  agent: test_agent


function_mapping_task:
    description: "Scans a directory for Python files and extracts function names matching a pattern with wildcard support."
    agent: function_agent
    expected_output: "List of function names matching the given pattern."
    parameters:
      - name: directory
        type: string
        required: true
        description: "The directory to search for Python functions."
      - name: pattern
        type: string
        required: true
        description: "Wildcard pattern for function names (e.g., '*call users' should return 'call_users()')."
    steps:
      - name: "Search for Python files"
        description: "Find all Python files in the directory."
        action: "search_python_files"
      - name: "Extract function names"
        description: "Parse the files and extract function names."
        action: "extract_functions"
      - name: "Filter functions by pattern"
        description: "Match functions against the wildcard pattern and return the result."
        action: "filter_functions"
