test_plan_task:
  description: >
    Conduct a thorough research about this test plan {topic}
    Make sure you find you review carefully step by step
  expected_output: >
    Validation for the test plan, return a thought about the test plan, add points for improvement
    and re-write the test plan in correct .md format as given
  agent: test_agent
