csv_task:
  agent: csv_agent
  description: >
    
    you will get a csv data: { input }
    read the rows below the `Element Name` header and change to a logical name based on the content
    if there is no content in the second row and below: STOP
  
    ** IMPORTANT **

    - if you're unable to find any content below the first row, do not invent new one, leave it as it is
    - element names should be displayed with underscores between each word as in python variable naming convention
    - change camel case words to pythonic variable naming convention
    - DO NOT refactor Element Name header

  capabilities: ['read', 'analyze', 'refactor']
  expected_output: correct naming columns
