csv_task:
  agent: csv_agent
  description: >
    you will get a csv data: {input}
    under `Element Name` column change to a logical name based on hole input
    
    **important**
      - if you're unable to find any content, do not invent new one, leave it as it is
      - element names should be displayed with underscores between each word as in python variable naming convention
      - change camel case words to pythonic variable naming convention
  capabilities: ['read', 'analyze', 'refactor']
  expected_output: correct naming columns
