task:
  agent: agent
  description: |
    
    you will get a sentence: {prompt}
    based on this prompt: fix grammar to a valid and understandable english
    
    ** IMPORTANT **
        - Return Invalid Question if the prompt is not a valid question

  expected_output: |
    Extracted relevant information from the provided sentence.
