grammar_task:
  description: |
    you will get a sentence: {prompt}
    based on this prompt: fix grammar to a valid and understandable english
  expected_output: Extracted relevant information from the provided sentence.
  agent: grammar_agent
