code_task:
  description: >
    Convert the test plan into a functional pytest script using the specified code format logic.

    **Test Plan:** Based on the `test_plan` provided from the tool.

    **Task:**
      - If the device is set to `smarttap` or `st`, all imports should be:
        ```
        from qasharedinfra.infra.smarttap.general_utils import get_file_size
        ```
        and the device instance should be:
        ```
        st: SmartTap = env.devices['Device_1']
        ```
      - If the device is set to `mi`, all imports should include `meetinginsights` instead of `smarttap`:
        ```
        from qasharedinfra.infra.meetinginsights.selenium.utils.custom_exceptions import ElementIsClickableException
        ```
        and replace `st` with:
        ```
        mi: MeetingInsightsSaaS = env.devices['Device_1']
        ```

    **Code Format:** `{original_code}`

    **Important Guidelines:**
      1. Always log each assertion. Example:
         ```
         assert <body>, log.bug('this is a bug')
         ```
      2. Replace Selenium’s `send_keys()` with `inject_text()`.
      3. The number of tests must match the test plan provided.
      4. Maintain simple and clean code logic.
      5. Each test must contain a docstring.

  expected_output: >
    A Python script with pytest tests.

  async_execution: false
  agent: code_agent
