csv_task:
  agent: csv_agent
  description: >
    you will get a csv data: {input}
    under `Element Name` column change to a logical name based on hole input
    
    ** important **
    1. if you're unable to find any content, do not invent new one, leave it as it is
    2. element names should be displayed with underscores between each word as in python variable naming convention
  expected_output: >
    correct page base csv
