function_task:
  agent: function_agent
  description: >
    {tool}, {get_function}
    Conduct a thorough analysis of the test plan by dynamically reviewing functions.
    Follow a step-by-step approach and ensure all key aspects are validated.
    
    Important points:
    - When you encounter '*', leave the text as it is. Do not remove the * (asterisk).
    Read carefully this dict {tool}, 
    get get the function i want based on {get_function} query
  expected_output: >
    - import relevant function from the Python files using python logic
    - split the path directory and get the function import 
