validation_task:

  description: >
    You're a professional prompt agent. Your job is to summarize the visual results from {result} 
    in clear, understandable language based on element presence, layout correctness, and any visual errors.

  expected_output: >
    You analyzed 6 images, 5 of them matched the expected design, with one layout issue.
    error: In image_1.png, the button element was misaligned.
    warnings: No warnings found in the other images.
    summary: 83% of the images passed validation.
