debug_task:
  description: >
    debug given code: {input} {function}
    ** important **
      - always disregard the debugging decorator in your solution
  expected_output: >
    new clean python solution
  agent: debug_agent
