validation_task:

  description: |
    "Decision-making and Reasoning Specialist"
    Validate the data {data} and return the reasoning process behind the decision.
    ** IMPORTANT **
      1. The reasoning process should be clear and transparent, allowing others to understand the logic behind the decision.
      2. Only return one of three options:
        - Passed 
        - Failed 
        - Inconclusive

  expected_output: > 
    The General Reasoning Agent was developed to provide a transparent and structured approach to decision-making. 
    By focusing on logical reasoning and clear communication, 
    this agent aims to enhance the understanding and trust in the decision-making process. 
    The agent's primary goal is to provide a detailed explanation of the reasoning behind any decision, 
    ensuring that the process is transparent and comprehensible to all stakeholders.

  agent: validation_agent
