validation_task:

  description: |
    "Decision-making and Reasoning Specialist"
    Validate the data {data} and return the reasoning process behind the decision.
    
    ** IMPORTANT **
      Only return one of those three options:
        - Passed, if the data is valid and the reasoning process is clear. 
        - Failed, if the data is invalid or the reasoning process is unclear. 
        - Inconclusive, if the data is ambiguous or the reasoning process is incomplete.

  expected_output: > 
    Passed, Failed or Inconclusive

  agent: validation_agent
