english_task:
  agent: english_agent
  description: >
    re-write this {prompt} to a valid english grammar
  expected_output: >
    correct english structure with correct grammar


image_task:
  agent: image_agent
  description: >
    analyze this {image} and visualize it
  expected_output: >
    correct analysis of the image
