function_task:
  agent: function_agent
  description: >
    Match user query {query} to the closest existing function in the provided function list: {available_functions}
    Extract all required function arguments from the query.
    return function name and extracted arguments.
      - "function_name": The matched function.
      - "arguments": function with arguments

    important_points:
      - Always choose from the available functions in {available_functions}.
      - Extract all necessary arguments dynamically from the query.
      - Do NOT generate new function logic.
  expected_output: >
      - Response format:
        best_function() or best_function() with arguments


code_task:
  agent: code_agent
  description: >
    Extract all required code arguments from the {response}.
    return valid code from the {response}.
  expected_output: >
      - Response format:
        best_code() or best_code() with arguments
