function_task:
  agent: function_agent
  description: >
    Match user query to the closest existing function in the provided function list.
    Do NOT generate new function names or code. 
    Only return the function name that best matches the user query.

    important_points: >
      - Always choose from the available functions in {available_functions}.
      - If no perfect match is found, select the closest function.
      - Do NOT generate new function logic, only return an existing function.
      - Response format: {query}
  expected_output: >
    The function name that best matches the user query.
